"""create_posts_analysis_comments_tables

Revision ID: cc6846487867
Revises: 
Create Date: 2026-03-07 02:54:59.999901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc6846487867'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('platform', sa.String(length=50), nullable=False, comment='Source platform: linkedin, twitter, reddit, etc.'),
    sa.Column('post_url', sa.String(length=2048), nullable=False, comment='Canonical URL of the post.'),
    sa.Column('author', sa.String(length=512), nullable=True, comment='Author name or handle.'),
    sa.Column('content', sa.Text(), nullable=False, comment='Full text body of the post.'),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False, comment='Number of comments/replies on the post.'),
    sa.Column('post_timestamp', sa.DateTime(timezone=True), nullable=True, comment='Original publication timestamp of the post.'),
    sa.Column('source_query', sa.String(length=1024), nullable=True, comment='Search query that discovered this post.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_url')
    )
    op.create_index(op.f('ix_posts_platform'), 'posts', ['platform'], unique=False)
    op.create_index('ix_posts_platform_url', 'posts', ['platform', 'post_url'], unique=False)
    op.create_table('comment_candidates',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False, comment='Full text of the generated comment.'),
    sa.Column('score', sa.Float(), nullable=False, comment='Quality score assigned by the judge agent (0.0–1.0).'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Lifecycle status: draft → reviewed → selected / rejected.'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Iteration number within the debate loop.'),
    sa.Column('critique', sa.Text(), nullable=True, comment='Last critic feedback received for this comment.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_candidates_post_id'), 'comment_candidates', ['post_id'], unique=False)
    op.create_table('post_analysis',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False, comment='0.0–1.0 relevance to the target problem.'),
    sa.Column('opportunity_score', sa.Float(), nullable=False, comment='0.0–1.0 opportunity to engage meaningfully.'),
    sa.Column('intent', sa.String(length=255), nullable=True, comment='Detected intent: question, rant, recommendation, etc.'),
    sa.Column('emotion', sa.String(length=255), nullable=True, comment='Dominant emotional tone: frustration, curiosity, etc.'),
    sa.Column('reasoning', sa.Text(), nullable=True, comment='Free-form reasoning from the analysis agent.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_analysis_post_id'), 'post_analysis', ['post_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_analysis_post_id'), table_name='post_analysis')
    op.drop_table('post_analysis')
    op.drop_index(op.f('ix_comment_candidates_post_id'), table_name='comment_candidates')
    op.drop_table('comment_candidates')
    op.drop_index('ix_posts_platform_url', table_name='posts')
    op.drop_index(op.f('ix_posts_platform'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
